### ISSUE TITLE
[词缀]新增冥法等3个词缀

### ISSUE THREAD

**Issue by Libellule505** [auioc/ExtraChampions#3]
1. 冥法necromancer（默认三星及以上才可以获得）：每15秒赋予10格内亡灵生物力量、速度、急迫，等级等于精英怪星级-1，持续15秒。
   2. 领袖leader（默认三星及以上才可以获得）：每15秒赋予10格内自己以外的敌对生物（对玩家的）抗性提升3，持续15秒。
   3. 暗影shadow：在亮度小于8的位置获得隐身，持续3秒。

**Comment by WakelessSloth56** [comment]
默认配置功能将统一于新的议题中追踪。https://github.com/auioc/ExtraChampions/issues/4
