### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by hkkl-VoeD** [auioc/ExtraChampions#9]
java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "top.theillusivec4.champions.common.config.ChampionsConfig.affixes" is nul

[crash-2022-05-08_15.15.23-server.txt](https://github.com/auioc/ExtraChampions/files/8646993/crash-2022-05-08_15.15.23-server.txt)
l

**Comment by WakelessSloth56** [comment]
We tested it many times but could not reproduce the problem.

You can try the following:
- Delete all relevant config files
- Disable other mods

If the problem still exists, please report more information, such as the full debug log.

**Comment by hkkl-VoeD** [comment]
I removed all mods and the server started up.

After that, I started sorting and looking for which mod is conflicting.
I was surprised when I discovered that this author's mods (https://www.curseforge.com/members/sketch_macaw/projects ) conflict with extrachampions.

After that, I added and removed his mods several times to verify this.
Then I returned all the mods except for his projects and the server crashed again.

I don't know if this will help you or not, but apparently there are a lot of conflicts.

In singleplayer everything works well with all mods.

**Comment by WakelessSloth56** [comment]
You can try this dev build:

> https://github.com/auioc/ExtraChampions/actions/runs/2304678830
> (Download the artifact, use the JAR file without the "forgelib" suffix.)

If the problem is fixed, please reply, I will release a new version.

**Comment by hkkl-VoeD** [comment]
Yes, that fixed the bug.
The server starts with all the mods that I have installed.

Well done!

Спасибо 🍉
